version: '3'
services:

  server:
    image: deev-server:latest
    container_name: fl_server
    environment:
      - SERVER_IP=0.0.0.0:9999
      - NUM_CLIENTS=10
      - NUM_ROUNDS=140
      - ALGORITHM=POC
      - POC=0.2
      - SOLUTION_NAME=None
      - DATASET=CIFAR10
      - MODEL=DNN
      - DECAY=0.005
    volumes:
      - ./logs:/logs
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
    

  client-0:
    image: deev-client:latest
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=0
      - NUM_CLIENTS=10
      - MODEL=DNN
      - CLIENT_SELECTION=POC
      - LOCAL_EPOCHS=1
      - SOLUTION_NAME=None
      - ALGORITHM=POC
      - DATASET=CIFAR10
      - POC=0.2
      - DECAY=0.005
      - TRANSMISSION_THRESHOLD=0.2
    volumes:
      - ./logs:/logs
      - ./Client/client.py:/client.py
    networks:
      - default
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5128163561434121"
      placement:
        constraints:
          - node.role==worker
          

  client-1:
    image: deev-client:latest
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=1
      - NUM_CLIENTS=10
      - MODEL=DNN
      - CLIENT_SELECTION=POC
      - LOCAL_EPOCHS=1
      - SOLUTION_NAME=None
      - ALGORITHM=POC
      - DATASET=CIFAR10
      - POC=0.2
      - DECAY=0.005
      - TRANSMISSION_THRESHOLD=0.2
    volumes:
      - ./logs:/logs
      - ./Client/client.py:/client.py
    networks:
      - default
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.6219703523368323"
      placement:
        constraints:
          - node.role==worker
          

  client-2:
    image: deev-client:latest
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=2
      - NUM_CLIENTS=10
      - MODEL=DNN
      - CLIENT_SELECTION=POC
      - LOCAL_EPOCHS=1
      - SOLUTION_NAME=None
      - ALGORITHM=POC
      - DATASET=CIFAR10
      - POC=0.2
      - DECAY=0.005
      - TRANSMISSION_THRESHOLD=0.2
    volumes:
      - ./logs:/logs
      - ./Client/client.py:/client.py
    networks:
      - default
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5677083320724886"
      placement:
        constraints:
          - node.role==worker
          

  client-3:
    image: deev-client:latest
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=3
      - NUM_CLIENTS=10
      - MODEL=DNN
      - CLIENT_SELECTION=POC
      - LOCAL_EPOCHS=1
      - SOLUTION_NAME=None
      - ALGORITHM=POC
      - DATASET=CIFAR10
      - POC=0.2
      - DECAY=0.005
      - TRANSMISSION_THRESHOLD=0.2
    volumes:
      - ./logs:/logs
      - ./Client/client.py:/client.py
    networks:
      - default
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.33200398703286815"
      placement:
        constraints:
          - node.role==worker
          

  client-4:
    image: deev-client:latest
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=4
      - NUM_CLIENTS=10
      - MODEL=DNN
      - CLIENT_SELECTION=POC
      - LOCAL_EPOCHS=1
      - SOLUTION_NAME=None
      - ALGORITHM=POC
      - DATASET=CIFAR10
      - POC=0.2
      - DECAY=0.005
      - TRANSMISSION_THRESHOLD=0.2
    volumes:
      - ./logs:/logs
      - ./Client/client.py:/client.py
    networks:
      - default
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.14467422710264"
      placement:
        constraints:
          - node.role==worker
          

  client-5:
    image: deev-client:latest
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=5
      - NUM_CLIENTS=10
      - MODEL=DNN
      - CLIENT_SELECTION=POC
      - LOCAL_EPOCHS=1
      - SOLUTION_NAME=None
      - ALGORITHM=POC
      - DATASET=CIFAR10
      - POC=0.2
      - DECAY=0.005
      - TRANSMISSION_THRESHOLD=0.2
    volumes:
      - ./logs:/logs
      - ./Client/client.py:/client.py
    networks:
      - default
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.35553828342013594"
      placement:
        constraints:
          - node.role==worker
          

  client-6:
    image: deev-client:latest
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=6
      - NUM_CLIENTS=10
      - MODEL=DNN
      - CLIENT_SELECTION=POC
      - LOCAL_EPOCHS=1
      - SOLUTION_NAME=None
      - ALGORITHM=POC
      - DATASET=CIFAR10
      - POC=0.2
      - DECAY=0.005
      - TRANSMISSION_THRESHOLD=0.2
    volumes:
      - ./logs:/logs
      - ./Client/client.py:/client.py
    networks:
      - default
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.833152097675453"
      placement:
        constraints:
          - node.role==worker
          

  client-7:
    image: deev-client:latest
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=7
      - NUM_CLIENTS=10
      - MODEL=DNN
      - CLIENT_SELECTION=POC
      - LOCAL_EPOCHS=1
      - SOLUTION_NAME=None
      - ALGORITHM=POC
      - DATASET=CIFAR10
      - POC=0.2
      - DECAY=0.005
      - TRANSMISSION_THRESHOLD=0.2
    volumes:
      - ./logs:/logs
      - ./Client/client.py:/client.py
    networks:
      - default
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.38626214793841407"
      placement:
        constraints:
          - node.role==worker
          

  client-8:
    image: deev-client:latest
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=8
      - NUM_CLIENTS=10
      - MODEL=DNN
      - CLIENT_SELECTION=POC
      - LOCAL_EPOCHS=1
      - SOLUTION_NAME=None
      - ALGORITHM=POC
      - DATASET=CIFAR10
      - POC=0.2
      - DECAY=0.005
      - TRANSMISSION_THRESHOLD=0.2
    volumes:
      - ./logs:/logs
      - ./Client/client.py:/client.py
    networks:
      - default
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.37043433714532925"
      placement:
        constraints:
          - node.role==worker
          

  client-9:
    image: deev-client:latest
    environment:
      - SERVER_IP=fl_server:9999
      - CLIENT_ID=9
      - NUM_CLIENTS=10
      - MODEL=DNN
      - CLIENT_SELECTION=POC
      - LOCAL_EPOCHS=1
      - SOLUTION_NAME=None
      - ALGORITHM=POC
      - DATASET=CIFAR10
      - POC=0.2
      - DECAY=0.005
      - TRANSMISSION_THRESHOLD=0.2
    volumes:
      - ./logs:/logs
      - ./Client/client.py:/client.py
    networks:
      - default
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.49394219721028976"
      placement:
        constraints:
          - node.role==worker
          

